### ISSUE TITLE
CallbackQueryHandler using Google-Apps-Script

### ISSUE THREAD

**Issue by ducky7788** [we684123/Google-Apps-Script-Telegram-Bot-Library#1]
Saw extensions available for python, and they are calling it CallbackQueryHandler.
I couldn't find any sources for such method in Google-Apps-Script.
Is it possible to update to have such method?

For example:
1. Inline keyboard button asks for first Option1 and Option2.
2. On callback, if Option1 chose, then editMessageReplyMarkup() with for Options 1.1, 1.2, 1.3. If Option 2 chose, then Options 2.1, 2.2, 2.3.

**Comment by we684123** [comment]
hi @ducky7788 OwO//
i am sorry 
but "Google-Apps-Script-Telegram-Bot-Library" just a "Library", it is not "Framework"

so... now i have not this plan to add "CallbackQueryHandler" 

----

but if you want to "CallbackQueryHandler"
maybe use [json-hook](https://github.com/we684123/json-hook) to reach

Is there anything I can do to help you?

**Comment by ducky7788** [comment]
Thanks for your reply @we684123 
I will try what you have suggested, i dont have much coding experiences.
Will take some time to trial and error of your json-hook library.
